// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | FeaturedProjectsSlice
  | StatisiticsSlice
  | AboutSlice
  | SkillsSliderSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProjectDocumentDataSlicesSlice = ScreenshotsSlice | HeaderWithTextSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Thumbnail field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes = PageDocument | ProjectDocument;

/**
 * Item in *About → Default → Primary → Tabs*
 */
export interface AboutSliceDefaultPrimaryTabsItem {
  /**
   * Title field in *About → Default → Primary → Tabs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.tabs[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * List field in *About → Default → Primary → Tabs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.tabs[].list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list: prismic.RichTextField;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Tabs field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.tabs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tabs: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryTabsItem>>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *FeaturedProjects → Default → Primary → Projects*
 */
export interface FeaturedProjectsSliceDefaultPrimaryProjectsItem {
  /**
   * Project field in *FeaturedProjects → Default → Primary → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.default.primary.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

/**
 * Primary content in *FeaturedProjects → Default → Primary*
 */
export interface FeaturedProjectsSliceDefaultPrimary {
  /**
   * Projects field in *FeaturedProjects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.default.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<
    Simplify<FeaturedProjectsSliceDefaultPrimaryProjectsItem>
  >;
}

/**
 * Default variation for FeaturedProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedProjects*
 */
type FeaturedProjectsSliceVariation = FeaturedProjectsSliceDefault;

/**
 * FeaturedProjects Shared Slice
 *
 * - **API ID**: `featured_projects`
 * - **Description**: FeaturedProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSlice = prismic.SharedSlice<
  "featured_projects",
  FeaturedProjectsSliceVariation
>;

/**
 * Primary content in *HeaderWithText → Default → Primary*
 */
export interface HeaderWithTextSliceDefaultPrimary {
  /**
   * Header field in *HeaderWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_text.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Text field in *HeaderWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for HeaderWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderWithText*
 */
type HeaderWithTextSliceVariation = HeaderWithTextSliceDefault;

/**
 * HeaderWithText Shared Slice
 *
 * - **API ID**: `header_with_text`
 * - **Description**: HeaderWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderWithTextSlice = prismic.SharedSlice<
  "header_with_text",
  HeaderWithTextSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Screenshots → Default → Primary → Screenshots*
 */
export interface ScreenshotsSliceDefaultPrimaryScreenshotsItem {
  /**
   * Screenshot field in *Screenshots → Default → Primary → Screenshots*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: screenshots.default.primary.screenshots[].screenshot
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screenshot: prismic.ImageField<never>;
}

/**
 * Primary content in *Screenshots → Default → Primary*
 */
export interface ScreenshotsSliceDefaultPrimary {
  /**
   * Screenshots field in *Screenshots → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: screenshots.default.primary.screenshots[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  screenshots: prismic.GroupField<
    Simplify<ScreenshotsSliceDefaultPrimaryScreenshotsItem>
  >;
}

/**
 * Default variation for Screenshots Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScreenshotsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScreenshotsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Screenshots*
 */
type ScreenshotsSliceVariation = ScreenshotsSliceDefault;

/**
 * Screenshots Shared Slice
 *
 * - **API ID**: `screenshots`
 * - **Description**: Screenshots
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScreenshotsSlice = prismic.SharedSlice<
  "screenshots",
  ScreenshotsSliceVariation
>;

/**
 * Item in *SkillsSlider → Default → Primary → Skills*
 */
export interface SkillsSliderSliceDefaultPrimarySkillsItem {
  /**
   * Icon field in *SkillsSlider → Default → Primary → Skills*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills_slider.default.primary.skills[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Background Color field in *SkillsSlider → Default → Primary → Skills*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: skills_slider.default.primary.skills[].background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Skill Name field in *SkillsSlider → Default → Primary → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills_slider.default.primary.skills[].skill_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skill_name: prismic.KeyTextField;
}

/**
 * Primary content in *SkillsSlider → Default → Primary*
 */
export interface SkillsSliderSliceDefaultPrimary {
  /**
   * Skills field in *SkillsSlider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills_slider.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<
    Simplify<SkillsSliderSliceDefaultPrimarySkillsItem>
  >;

  /**
   * Direction field in *SkillsSlider → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: skills_slider.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  direction: prismic.BooleanField;
}

/**
 * Default variation for SkillsSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SkillsSlider*
 */
type SkillsSliderSliceVariation = SkillsSliderSliceDefault;

/**
 * SkillsSlider Shared Slice
 *
 * - **API ID**: `skills_slider`
 * - **Description**: SkillsSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSliderSlice = prismic.SharedSlice<
  "skills_slider",
  SkillsSliderSliceVariation
>;

/**
 * Default variation for Statisitics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisiticsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Statisitics*
 */
type StatisiticsSliceVariation = StatisiticsSliceDefault;

/**
 * Statisitics Shared Slice
 *
 * - **API ID**: `statisitics`
 * - **Description**: Statisitics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisiticsSlice = prismic.SharedSlice<
  "statisitics",
  StatisiticsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryTabsItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      FeaturedProjectsSlice,
      FeaturedProjectsSliceDefaultPrimaryProjectsItem,
      FeaturedProjectsSliceDefaultPrimary,
      FeaturedProjectsSliceVariation,
      FeaturedProjectsSliceDefault,
      HeaderWithTextSlice,
      HeaderWithTextSliceDefaultPrimary,
      HeaderWithTextSliceVariation,
      HeaderWithTextSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ScreenshotsSlice,
      ScreenshotsSliceDefaultPrimaryScreenshotsItem,
      ScreenshotsSliceDefaultPrimary,
      ScreenshotsSliceVariation,
      ScreenshotsSliceDefault,
      SkillsSliderSlice,
      SkillsSliderSliceDefaultPrimarySkillsItem,
      SkillsSliderSliceDefaultPrimary,
      SkillsSliderSliceVariation,
      SkillsSliderSliceDefault,
      StatisiticsSlice,
      StatisiticsSliceVariation,
      StatisiticsSliceDefault,
    };
  }
}
