// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  rich_text: dynamic(() => import("./RichText")),
  skills_slider: dynamic(() => import("./SkillsSlider")),
};
